language: ruby
rvm:
  - 2.4.0

before_script:
- pwd
- ls -a
- mv config/database.yml.travis config/database.yml

script:
- bundle exec /usr/bin/env RAILS_ENV=test rake db:drop db:create db:reset
- bundle exec rspec spec

notifications:
  slack:
    on_success: change
    rooms:
    - camsys:lXMC55pg5oKxSTYW38zsB9jm#1click 