
# SMTP EMAIL CONFIG
SMTP_SERVER: "email-smtp.us-east-1.amazonaws.com"
SMTP_USER_NAME: "AKIAJHDZ3GEDRWOYMVNQ"
SMTP_PASSWORD: "Av2cXdGCUO0mK+HawYOYhmmZkdAH5B84qXEVCk7acro6"

# BOOKING PASSWORD ENCRYPTION
BOOKING_PASSWORD_ENCRYPTION_KEY: "baXWwUli4locihi3FvItK1EndrjMACF7"
