# This YML file sets ENV variables for the rspec test environment

# BOOKING PASSWORD ENCRYPTION
BOOKING_PASSWORD_ENCRYPTION_KEY: "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345"

# I18N
AVAILABLE_LOCALES: 'en,es,fr'
